In [35]:
import pandas as pd
from datetime import date
import numpy as np
from collections import OrderedDict
from dateutil.relativedelta import *

interest_rate = 0.045
years = 30
annual_payments = 12
principal = 240000
addl_principal = 0
start_date = (date(2018,1,1))

In [32]:
def amortize(principal, interest_rate, years, addl_principal=0, annual_payments=12, start_date=date.today()):

    pmt = -round(np.pmt(interest_rate/annual_payments, years*annual_payments, principal), 2)
    # initialize the variables to keep track of the periods and running balances
    p = 1
    beg_balance = principal
    end_balance = principal

    while end_balance > 0:

        # Recalculate the interest based on the current balance
        interest = round(((interest_rate/annual_payments) * beg_balance), 2)

        # Determine payment based on whether or not this period will pay off the loan
        pmt = min(pmt, beg_balance + interest)
        principal = pmt - interest

        # Ensure additional payment gets adjusted if the loan is being paid off
        addl_principal = min(addl_principal, beg_balance - principal)
        end_balance = beg_balance - (principal + addl_principal)

        yield OrderedDict([('Month',start_date),
                           ('Period', p),
                           ('Begin Balance', beg_balance),
                           ('Payment', pmt),
                           ('Principal', principal),
                           ('Interest', interest),
                           ('Additional_Payment', addl_principal),
                           ('End Balance', end_balance)])

        # Increment the counter, balance and date
        p += 1
        start_date += relativedelta(months=1)
        beg_balance = end_balance

In [36]:
schedule = pd.DataFrame(amortize(principal, interest_rate, years, addl_principal, annual_payments, start_date))
schedule

,Month,Period,Begin Balance,Payment,Principal,Interest,Additional_Payment,End Balance
0,2018-01-01,1,240000.00,1216.04,316.04,900.00,0,239683.96
1,2018-02-01,2,239683.96,1216.04,317.23,898.81,0,239366.73
2,2018-03-01,3,239366.73,1216.04,318.41,897.63,0,239048.32
3,2018-04-01,4,239048.32,1216.04,319.61,896.43,0,238728.71
4,2018-05-01,5,238728.71,1216.04,320.81,895.23,0,238407.90
5,2018-06-01,6,238407.90,1216.04,322.01,894.03,0,238085.89
6,2018-07-01,7,238085.89,1216.04,323.22,892.82,0,237762.67
7,2018-08-01,8,237762.67,1216.04,324.43,891.61,0,237438.24
8,2018-09-01,9,237438.24,1216.04,325.65,890.39,0,237112.59
9,2018-10-01,10,237112.59,1216.04,326.87,889.17,0,236785.72
10,2018-11-01,11,236785.72,1216.04,328.09,887.95,0,236457.63
11,2018-12-01,12,236457.63,1216.04,329.32,886.72,0,236128.31
12,2019-01-01,13,236128.31,1216.04,330.56,885.48,0,235797.75
13,2019-02-01,14,235797.75,1216.04,331.80,884.24,0,235465.95
14,2019-03-01,15,235465.95,1216.04,333.04,883.00,0,235132.91
15,2019-04-01,16,235132.91,1216.04,334.29,881.75,0,234798.62
16,2019-05-01,17,234798.62,1216.04,335.55,880.49,0,234463.07
17,2019-06-01,18,234463.07,1216.04,336.80,879.24,0,234126.27
18,2019-07-01,19,234126.27,1216.04,338.07,877.97,0,233788.20
19,2019-08-01,20,233788.20,1216.04,339.33,876.71,0,233448.87
20,2019-09-01,21,233448.87,1216.04,340.61,875.43,0,233108.26
21,2019-10-01,22,233108.26,1216.04,341.88,874.16,0,232766.38
22,2019-11-01,23,232766.38,1216.04,343.17,872.87,0,232423.21
23,2019-12-01,24,232423.21,1216.04,344.45,871.59,0,232078.76
24,2020-01-01,25,232078.76,1216.04,345.74,870.30,0,231733.02
25,2020-02-01,26,231733.02,1216.04,347.04,869.00,0,231385.98
26,2020-03-01,27,231385.98,1216.04,348.34,867.70,0,231037.64
27,2020-04-01,28,231037.64,1216.04,349.65,866.39,0,230687.99
28,2020-05-01,29,230687.99,1216.04,350.96,865.08,0,230337.03
29,2020-06-01,30,230337.03,1216.04,352.28,863.76,0,229984.75
...,...,...,...,...,...,...,...,...
331,2045-08-01,332,33359.43,1216.04,1090.94,125.10,0,32268.49
332,2045-09-01,333,32268.49,1216.04,1095.03,121.01,0,31173.46
333,2045-10-01,334,31173.46,1216.04,1099.14,116.90,0,30074.32
334,2045-11-01,335,30074.32,1216.04,1103.26,112.78,0,28971.06
335,2045-12-01,336,28971.06,1216.04,1107.40,108.64,0,27863.66
336,2046-01-01,337,27863.66,1216.04,1111.55,104.49,0,26752.11
337,2046-02-01,338,26752.11,1216.04,1115.72,100.32,0,25636.39
338,2046-03-01,339,25636.39,1216.04,1119.90,96.14,0,24516.49
339,2046-04-01,340,24516.49,1216.04,1124.10,91.94,0,23392.39
340,2046-05-01,341,23392.39,1216.04,1128.32,87.72,0,22264.07
341,2046-06-01,342,22264.07,1216.04,1132.55,83.49,0,21131.52
342,2046-07-01,343,21131.52,1216.04,1136.80,79.24,0,19994.72
343,2046-08-01,344,19994.72,1216.04,1141.06,74.98,0,18853.66
344,2046-09-01,345,18853.66,1216.04,1145.34,70.70,0,17708.32
345,2046-10-01,346,17708.32,1216.04,1149.63,66.41,0,16558.69
346,2046-11-01,347,16558.69,1216.04,1153.94,62.10,0,15404.75
347,2046-12-01,348,15404.75,1216.04,1158.27,57.77,0,14246.48
348,2047-01-01,349,14246.48,1216.04,1162.62,53.42,0,13083.86
349,2047-02-01,350,13083.86,1216.04,1166.98,49.06,0,11916.88
350,2047-03-01,351,11916.88,1216.04,1171.35,44.69,0,10745.53
351,2047-04-01,352,10745.53,1216.04,1175.74,40.30,0,9569.79
352,2047-05-01,353,9569.79,1216.04,1180.15,35.89,0,8389.64
353,2047-06-01,354,8389.64,1216.04,1184.58,31.46,0,7205.06
354,2047-07-01,355,7205.06,1216.04,1189.02,27.02,0,6016.04
355,2047-08-01,356,6016.04,1216.04,1193.48,22.56,0,4822.56
356,2047-09-01,357,4822.56,1216.04,1197.96,18.08,0,3624.60
357,2047-10-01,358,3624.60,1216.04,1202.45,13.59,0,2422.15
358,2047-11-01,359,2422.15,1216.04,1206.96,9.08,0,1215.19
359,2047-12-01,360,1215.19,1216.04,1211.48,4.56,0,3.71
360,2048-01-01,361,3.71,3.72,3.71,0.01,0,0.00